apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
      initContainers:
        - 
          name: copy-jekyll-site
          image: kodekloud/jekyll
          command: [ "jekyll", "new", "/site"]
          volumeMounts:
          - mountPath: /site
            name:  site
      containers:
        - 
          name: jekyll
          image: kodekloud/jekyll-serve
          volumeMounts:
          - mountPath: /site
            name: site
      volumes:
         - 
          name: site
          persistentVolumeClaim:
           claimName: jekyll-site
---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  ports:
    - 
      name: http
      port: 8080
      protocol: TCP
      targetPort: 4000
      nodePort: 30097
  selector:
    run: jekyll
  type: NodePort