apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpru-deployment
  namespace: demo-nginx02
spec:
  selector:
    matchLabels:
      app: nginx-pru
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-pru
    spec:
      containers:
      - name: nginx-pru
        image: docker.prod.walmart.com/strati-customer-success/demo-dic10:0.0.10
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: nginxpru-deployment
  namespace: demo-nginx02
  labels:
    run: nginx-pru
spec:
  ports:
  - port: 90
    protocol: TCP
  selector:
    run: nginx-pru

