apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deploy
  labels:
    app: go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: christianhxc/api-hello:1.0
        ports:
        - containerPort: 8080
